[project]
name = "audio-from-slow-motion-video"
version = "0.1.0"
description = "Reproduce sound using video frame luminance values."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "scipy>=1.16.3",
    "tqdm>=4.67.1",
]
